---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: f0b4dfc2cae5e12ccbede4a075c894d33a50ad0d
      fabric8.io/iconUrl: img/icons/camel.svg
      fabric8.io/git-branch: master
      prometheus.io/scrape: "true"
      prometheus.io/port: "9779"
    labels:
      expose: "true"
      app: fuse-netty-proxy
      provider: fabric8
      version: com.redhat.camelProxyJavaDSL
      group: com.redhat.camelProxyJavaDSL
    name: fuse-netty-proxy
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: proxy
      port: 8088
      protocol: TCP
      targetPort: 8088
    selector:
      app: fuse-netty-proxy
      provider: fabric8
      group: com.redhat.camelProxyJavaDSL
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      fabric8.io/git-commit: f0b4dfc2cae5e12ccbede4a075c894d33a50ad0d
      fabric8.io/iconUrl: img/icons/camel.svg
      fabric8.io/git-branch: master
      fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=fuse-netty-proxy&var-version=com.redhat.camelProxyJavaDSL
    labels:
      app: fuse-netty-proxy
      provider: fabric8
      version: com.redhat.camelProxyJavaDSL
      group: com.redhat.camelProxyJavaDSL
    name: fuse-netty-proxy
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: fuse-netty-proxy
        provider: fabric8
        group: com.redhat.camelProxyJavaDSL
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: f0b4dfc2cae5e12ccbede4a075c894d33a50ad0d
          fabric8.io/iconUrl: img/icons/camel.svg
          fabric8.io/git-branch: master
          fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=fuse-netty-proxy&var-version=com.redhat.camelProxyJavaDSL
        labels:
          app: fuse-netty-proxy
          provider: fabric8
          version: com.redhat.camelProxyJavaDSL
          group: com.redhat.camelProxyJavaDSL
      spec:
        containers:
        - env:
          - name: SPRING_APPLICATION_JSON
            value: '{"server":{"undertow":{"io-threads":1, "worker-threads":2 }}}'
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: fuse-netty-proxy:com.redhat.camelProxyJavaDSL
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: "1.0"
              memory: 256Mi
            requests:
              cpu: "0.2"
              memory: 256Mi
          securityContext:
            privileged: false
