name: build
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: temurin
      - run: mvn --batch-mode --update-snapshots package
      - uses: docker/metadata-action@v4
        id: metadata
        with:
          images: |
            quay.io/rh_integration/3scale-fuse-camel-proxy
          tags: |
            type=semver,pattern={{version}}
            type=sha
      - uses: docker/setup-qemu-action@master
        with:
          platforms: ppc64le,s390x
      - uses: docker/setup-buildx-action@master
      - uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/ppc64le,linux/s390x
          tags: ${{ steps.metadata.outputs.tags }}
          push: true
